"""Add authentication tables

Revision ID: 402fae8fb853
Revises: 5e8fcfbb1d51
Create Date: 2025-11-28 04:03:31.518456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402fae8fb853'
down_revision = '5e8fcfbb1d51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
