"""add deleted_at to faces

Revision ID: 59cd34d78697
Revises: bb29673e3722
Create Date: 2025-11-29 17:33:01.733934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cd34d78697'
down_revision = 'bb29673e3722'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faces', 'deleted_at')
    # ### end Alembic commands ###
