"""autogen fix

Revision ID: 73a73580f185
Revises: 9da5bdc3edfb
Create Date: 2025-11-28 04:58:44.850470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a73580f185'
down_revision = '9da5bdc3edfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
