"""create face and photo tables

Revision ID: 81b2244cc55a
Revises: 1bb53eaa10ed
Create Date: 2025-12-27 12:04:40.349929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b2244cc55a'
down_revision = '1bb53eaa10ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('avg_similarity', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('representative_face_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('merged_into_cluster_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.String(length=1000), nullable=True),
    sa.Column('face_ids', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_into_cluster_id'], ['face_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['representative_face_id'], ['faces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_clusters_album_id'), 'face_clusters', ['album_id'], unique=False)
    op.create_index(op.f('ix_face_clusters_cluster_label'), 'face_clusters', ['cluster_label'], unique=False)
    op.create_index(op.f('ix_face_clusters_id'), 'face_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_face_clusters_job_id'), 'face_clusters', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_clusters_job_id'), table_name='face_clusters')
    op.drop_index(op.f('ix_face_clusters_id'), table_name='face_clusters')
    op.drop_index(op.f('ix_face_clusters_cluster_label'), table_name='face_clusters')
    op.drop_index(op.f('ix_face_clusters_album_id'), table_name='face_clusters')
    op.drop_table('face_clusters')
    # ### end Alembic commands ###
