"""describe change

Revision ID: 9da5bdc3edfb
Revises: 4df082f55528
Create Date: 2025-11-28 04:44:27.862228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da5bdc3edfb'
down_revision = '4df082f55528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
